### ISSUE TITLE
Typo in the AWS_COGNITO_JWSK_PATH name?

### ISSUE THREAD

**Issue by erhhung** [borisrozumnuk/cognitojwt#13]
Shouldn't the `AWS_COGNITO_JWSK_PATH` environment variable be named `AWS_COGNITO_`**`JWKS`**`_PATH`?

**Comment by rangerthegood** [comment]
I've added a pull request to fix this, https://github.com/borisrozumnuk/cognitojwt/pull/14

**Comment by joshfriend** [comment]
@borisrozumnuk can you please make a new release to fix this? The latest on PyPI is from May 7 last year.

**Comment by borisrozumnuk** [comment]
> @borisrozumnuk can you please make a new release to fix this? The latest on PyPI is from May 7 last year.

@joshfriend  done, [1.3.0](https://pypi.org/project/cognitojwt/1.3.0/) available now

**Comment by joshfriend** [comment]
amazing ❤️ thank you!
