### ISSUE TITLE
Module 'cognitojwt' has no attribute 'decode' when deploying on lambda

### ISSUE THREAD

**Issue by A1exandre** [borisrozumnuk/cognitojwt#17]
Hi, 

I'm trying to use this on a lambda.

So I moved your package in a zip along with my function and uploaded.
![image](https://user-images.githubusercontent.com/15021331/131501001-9cb92b3f-4bd6-4f5a-9627-1224e358fa25.png)

Then my code is straightforward and works on my laptop - it's the same as the example:
```
import cognitojwt

id_token = '....'
REGION = 'us-east-2'
USERPOOL_ID = 'us-east-2_XXXX'
APP_CLIENT_ID = '5XXXXX'
verified_claims: dict = cognitojwt.decode(id_token,REGION,USERPOOL_ID, app_client_id=APP_CLIENT_ID, testmode=True)

print (verified_claims)`

However, when running to lambda i get
> "errorMessage": "module 'cognitojwt' has no attribute 'decode'",
```

I think this has to do with how when doing pip install cognitojwt**[sync]**, the [sync] makes something happens that is not reproduced by just moving the cognitojwt in a zip folder... 

Any idea for me to investigate would be appreciated :)

**Comment by CatCanCreate** [comment]
> Hi,
> 
> I'm trying to use this on a lambda.
> 
> So I moved your package in a zip along with my function and uploaded.
> ![image](https://user-images.githubusercontent.com/15021331/131501001-9cb92b3f-4bd6-4f5a-9627-1224e358fa25.png)
> 
> Then my code is straightforward and works on my laptop - it's the same as the example:
> 
> ```
> import cognitojwt
> 
> id_token = '....'
> REGION = 'us-east-2'
> USERPOOL_ID = 'us-east-2_XXXX'
> APP_CLIENT_ID = '5XXXXX'
> verified_claims: dict = cognitojwt.decode(id_token,REGION,USERPOOL_ID, app_client_id=APP_CLIENT_ID, testmode=True)
> 
> print (verified_claims)`
> 
> However, when running to lambda i get
> > "errorMessage": "module 'cognitojwt' has no attribute 'decode'",
> ```
> 
> I think this has to do with how when doing pip install cognitojwt**[sync]**, the [sync] makes something happens that is not reproduced by just moving the cognitojwt in a zip folder...
> 
> Any idea for me to investigate would be appreciated :)

https://github.com/borisrozumnuk/cognitojwt/blob/6a9b452a823b560552476c6c7cc81f462bd2e70c/cognitojwt/__init__.py#L13

try to install requests (pip install requests)

**Comment by A1exandre** [comment]
Yes - indeed. 

OK so to recape & close:
- Problem was that I was missing some parts of the dependency tree of Requests (given I copied manually as I could not use pip in my environment)
- One reason was that cognitojwt/__init__.py was failing silently so I did not spot this
- Solution was quite obvious: install the package dependency properly (i.e. with all sub-dependencies)

Thanks!
