### ISSUE TITLE
Security vulnerability in `ecdsa`

### ISSUE THREAD

**Issue by YaraslauZhylko** [borisrozumnuk/cognitojwt#20]
`cognitojwt` depends on `python-jose`, which in turn depends on `ecdsa`.
The latter has a **high** level vulnerability: https://github.com/advisories/GHSA-wj6h-64fc-37mp

Seems like `ecdsa` is not going to fix the issue: https://github.com/tlsfuzzer/python-ecdsa/security/advisories/GHSA-wj6h-64fc-37mp
And `python-jose` has not had updates for ages.

Is it possible to switch from using `python-jose` to any other, more frequently updated library?
For example, [joserfc](https://github.com/authlib/joserfc)?

**Comment by borisrozumnuk** [comment]
@YaraslauZhylko Pull Request for such an update would be welcomed
