### ISSUE TITLE
When requests is not installed it gives wrong error messages.

### ISSUE THREAD

**Issue by MohiuddinSumon** [borisrozumnuk/cognitojwt#21]
I was getting AttributeError: module 'cognitojwt' has no attribute 'decode' but the actual issue was I didn't had requests installed. 

try:
    import requests
    from .jwt_sync import decode
    __all__.append('decode')
except ImportError:
    pass
    
   this explicit pass should be handled

**Comment by MohiuddinSumon** [comment]
@borisrozumnuk I tried to install sync always gets error:

❯ pip install cognitojwt[sync]
zsh: no matches found: cognitojwt[sync]

but installing > pip install cognitojwt works.

**Comment by borisrozumnuk** [comment]
@MohiuddinSumon  try `pip install cognitojwt\[sync]`, it should work for you

**Comment by MohiuddinSumon** [comment]
thanks , pip install 'cognitojwt[sync]' this commands also works but these doesn't solve the total problem
